version: '3.8'

services:
  apigw-talybu:
    build: .
    image: apigw-image-talybu
    ports:
      - "22000:22000"
    volumes:
      - ./src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=22000
      - NATS_SERVERS=nats://nats-talybu:4222
    networks:
      - talybu-network

networks:
  talybu-network:
    external: true
    name: talybu_network