
export const PRODUCTS_SERVICE = "PRODUCTS_SERVICE";
export const ORDER_HEADERS_PURCHASE_SERVICE = "ORDER_HEADERS_PURCHASE_SERVICE";
export const ORDER_HEADERS_SUPPLY_SERVICE = "ORDER_HEADERS_SUPPLY_SERVICE";
export const ORDER_DETAILS_PURCHASE_SERVICE = "ORDER_DETAILS_PURCHASE_SERVICE";
export const ORDER_DETAILS_SUPPLY_SERVICE = "ORDER_DETAILS_SUPPLY_SERVICE";
