-- AlterTable
ALTER TABLE "TBL_PURCHASE_ORDER" ALTER COLUMN "status" SET DEFAULT 'PENDIENTE';

-- CreateTable
CREATE TABLE "TBL_PURCHARSE_ORDER_ITEMS" (
    "id" SERIAL NOT NULL,
    "productId" INTEGER NOT NULL,
    "quantity" INTEGER NOT NULL,
    "price" DOUBLE PRECISION NOT NULL,
    "tBL_PURCHASE_ORDERId" INTEGER,

    CONSTRAINT "TBL_PURCHARSE_ORDER_ITEMS_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "TBL_PURCHARSE_ORDER_ITEMS" ADD CONSTRAINT "TBL_PURCHARSE_ORDER_ITEMS_tBL_PURCHASE_ORDERId_fkey" FOREIGN KEY ("tBL_PURCHASE_ORDERId") REFERENCES "TBL_PURCHASE_ORDER"("id") ON DELETE SET NULL ON UPDATE CASCADE;
